AWSTemplateFormatVersion: "2010-09-09"

Description: Sample Template for deploying DemoApp using Getting Started with AWS CodePipeline demo

Parameters:
  EnvName:
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    Type: String
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.

  LambdaHandlerPath:
    Description: Path of a Lambda Handler.
    Type: String
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
    Default: index.lambda_handler
    

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub lambda-role-${EnvName}
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /

  LambdaFunction:
    Type: AWS::Lambda::Function
    Metadata:
      guard:
        SuppressedRules:
          - LAMBDA_INSIDE_VPC
          - LAMBDA_FUNCTION_PUBLIC_ACCESS_PROHIBITED
    Properties:
      FunctionName: !Sub lambda-function-${EnvName}
      Description: LambdaFunction using python3.12.
      Runtime: python3.12
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              print(json.dumps(event))
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
      Handler: !Sub ${LambdaHandlerPath}
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt LambdaRole.Arn
      Environment:
        Variables:
          ENV: !Ref EnvName
          TZ: UTC

Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value: !GetAtt LambdaRole.Arn


  LambdaFunctionName:
    Value: !Ref LambdaFunction

  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value: !GetAtt LambdaFunction.Arn

